### ISSUE TITLE
JS error when building any XCode example

### ISSUE THREAD

**Issue by gregorym** [ptmt/react-native-desktop#23]
this is what I get when I build any example and create a new project.

```
/Users/me/code/react-native-desktop/local-cli/cli.js:53
  const setupEnvScript = /^win/.test(process.platform)
  ^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
Process terminated. Press <enter> to close the window
```

**Comment by ptmt** [comment]
What Node version do you use? ’node -v’

**Comment by gregorym** [comment]
v0.12.2

**Comment by ptmt** [comment]
Sorry, React Native works only on Node 4.2+

**Comment by gregorym** [comment]
Work after reinstalling. Thanks
